### ISSUE TITLE
"not found" when running in the terraform light docker image v0.11.8

### ISSUE THREAD

**Issue by ukabu** [mevansam/terraform-provider-cf#136]
I'm trying to use the cf provider in a Concourse pipeline.
extract from task yml:
```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: "0.11.8"
```
The provider binary is dowloaded from github:
```
curl -L -o terraform.d/plugins/linux_amd64/terraform-provider-cf https://github.com/mevansam/terraform-provider-cf/releases/download/0.9.8/terraform-provider-cf_linux_amd64 
chmod +x terraform.d/plugins/linux_amd64/terraform-provider-cf
```
When I try to run it, I get a "not found" error.
Same Binary running on my laptop output as expected
```
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```

Does it depends on libraries not present in terraform docker image?
Do I have to have the `cf` cli present?
